AdamPersonalCapstone/AdamPersonalCapstone/Controllers/RatingController.cs
using AdamPersonalCapstone.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace AdamPersonalCapstone.Controllers
{
    public class RatingController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        Employee employee;
        Customer customer;
        public ActionResult eRate(int rating, string id)
        {
            employee = db.Employees.Where(c => c.ApplicationId == id).SingleOrDefault();
            employee.employeeRating += rating;
            employee.rateCount += 1;
            employee.averageRate = (employee.employeeRating / employee.rateCount);
            db.Entry(employee).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index", "Customer");
        }
        // GET: Rating
        public ActionResult Index()
        {
            return View();
        }
    }
}

AdamPersonalCapstone/AdamPersonalCapstone/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdamPersonalCapstone.Models;
using Microsoft.AspNet.Identity;

namespace AdamPersonalCapstone.Controllers
{
    public class TicketsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tickets
        public ActionResult Index()
        {
            var tickets = db.Tickets.Include(t => t.Customer).Include(t => t.Device).Include(t => t.Employee);
            return View(tickets.ToList());
        }
        public ActionResult CreateTicket(int id)
        {
            var cuserId = User.Identity.GetUserId();
            var customer = db.Customers.Where(c => c.ApplicationId == cuserId).FirstOrDefault();
            Ticket ticket = new Ticket();
            ticket.DeviceId = id;
            ticket.CustomerId = customer.CustomerId;
            db.Tickets.Add(ticket);
            db.SaveChanges();
            return View();
        }
        public ActionResult Claim()
        {
            var eUserId = User.Identity.GetUserId();
            var currentEmployee = db.Employees.Where(e => e.ApplicationId == eUserId).FirstOrDefault();
            var employeeTickets = db.Tickets.Where(t => t.EmployeeId == currentEmployee.EmployeeId && t.isClaimed == true && t.isCompleted == false);
            return View(employeeTickets);
        }
        public ActionResult Complete()
        {
            var eUserId = User.Identity.GetUserId();
            var currentEmployee = db.Employees.Where(e => e.ApplicationId == eUserId).FirstOrDefault();
            var employeeTickets = db.Tickets.Where(t => t.EmployeeId == currentEmployee.EmployeeId && t.isCompleted == true);
            return View(employeeTickets);
        }

        public ActionResult Pending()
        {
            var tickets = db.Tickets.Where(t => t.isClaimed == false && t.isCompleted == false).Include(t => t.Customer).Include(t => t.Device).Include(t => t.Employee);
            return View(tickets.ToList());
        }
        // GET: Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Tickets/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "ApplicationId");
            ViewBag.DeviceId = new SelectList(db.Devices, "DevicesId", "Name");
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "ApplicationId");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TicketId,EmployeeId,CustomerId,DeviceId,MessageSent,MessageReceived,Subject,Message")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                var cuserId = User.Identity.GetUserId();
                var customer = db.Customers.Where(c => c.ApplicationId == cuserId).FirstOrDefault();
                ticket.CustomerId = customer.CustomerId;
                db.Tickets.Add(ticket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "ApplicationId", ticket.CustomerId);
            ViewBag.DeviceId = new SelectList(db.Devices, "DevicesId", "Name", ticket.DeviceId);
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "ApplicationId", ticket.EmployeeId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "ApplicationId", ticket.CustomerId);
            ViewBag.DeviceId = new SelectList(db.Devices, "DevicesId", "Brand", ticket.DeviceId);
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "ApplicationId", ticket.EmployeeId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "TicketId,EmployeeId,CustomerId,DeviceId,MessageSent,MessageReceived,Subject,Message")]*/ Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "ApplicationId", ticket.CustomerId);
            ViewBag.DeviceId = new SelectList(db.Devices, "DevicesId", "Brand", ticket.DeviceId);
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "ApplicationId", ticket.EmployeeId);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = db.Tickets.Find(id);
            db.Tickets.Remove(ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdamPersonalCapstone/AdamPersonalCapstone/Views/Shared/_HomePage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NeighborNerd</title>
    @Styles.Render("~/Content/homepage.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NeighborNerd", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (User.IsInRole("Owner"))
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Pending Tickets", "Pending", "Tickets")</li>
                        <li>@Html.ActionLink("Claimed Tickets", "Claim", "Tickets")</li>
                        <li>@Html.ActionLink("Completed Tickets", "Complete", "Tickets")</li>
                        <li>@Html.ActionLink("Employee Details", "Details", "Employees")</li>
                        <li>@Html.ActionLink("Customer Details", "Details", "Customers")</li>
                    </ul>
                }
                @if (User.IsInRole("Employee"))
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Pending Tickets", "Pending", "Tickets")</li>
                        <li>@Html.ActionLink("Claimed Tickets", "Claim", "Tickets")</li>
                        <li>@Html.ActionLink("Completed Tickets", "Complete", "Tickets")</li>
                    </ul>
                }
                @if (User.IsInRole("Customer"))
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Tickets", "Index", "Tickets")</li>
                        <li>@Html.ActionLink("Device Profile", "Index", "CustomerDevicesJTables")</li>
                        <li>@Html.ActionLink("Pay For Service", "Payment", "Customers")</li>
                        <li>@Html.ActionLink("Coverage Map", "Map", "Customers")</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Neighborhood Nerd LLC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AdamPersonalCapstone/AdamPersonalCapstone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NeighborNerd</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <img src="~/Content/Image/nhn.png" style="width: 40px; height: 40px" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NeighborNerd", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse"> 
                @if (User.IsInRole("Owner"))
                {
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pending Tickets", "Pending", "Tickets")</li>
                    <li>@Html.ActionLink("Claimed Tickets", "Claim", "Tickets")</li>
                    <li>@Html.ActionLink("Completed Tickets", "Complete", "Tickets")</li>
                    <li>@Html.ActionLink("Employee Details", "Details", "Employees")</li>
                    <li>@Html.ActionLink("Customer Details", "Details", "Customers")</li>
                </ul>
                }
                @if (User.IsInRole("Employee"))
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Pending Tickets", "Pending", "Tickets")</li>
                        <li>@Html.ActionLink("Claimed Tickets", "Claim", "Tickets")</li>
                        <li>@Html.ActionLink("Completed Tickets", "Complete", "Tickets")</li>
                    </ul>
                }
                @if (User.IsInRole("Customer"))
                {
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Tickets", "Index", "Tickets")</li>
                <li>@Html.ActionLink("Device Profile", "Index", "CustomerDevicesJTables")</li>
                <li>@Html.ActionLink("Pay For Service", "Payment", "Customers")</li>
                <li>@Html.ActionLink("Coverage Map", "Map", "Customers")</li>
            </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Neighborhood Nerd LLC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AdamPersonalCapstone/AdamPersonalCapstone/Views/Shared/_Rating.cshtml
@model AdamPersonalCapstone.Models.Review

<h2>Please Rate Your Nerd! **if this loads then this partial view is working correctly.</h2>
<br />
<button class="button1" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 1, id = Model.ApplicationId})'"></button>
<button class="button2" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 2, id = Model.ApplicationId})'"></button>
<button class="button3" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 3, id = Model.ApplicationId})'"></button>
<button class="button4" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 4, id = Model.ApplicationId})'"></button>
<button class="button5" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 5, id = Model.ApplicationId})'"></button>

AdamPersonalCapstone/AdamPersonalCapstone/Views/Shared/_StarRating.cshtml
@model AdamPersonalCapstone.Models.Review

<h2>Please Rate Your Nerd! **if this loads then this partial view is working correctly.</h2>
<br />
<button class="button1" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 1, id = Model.ApplicationId})'"></button>
<button class="button2" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 2, id = Model.ApplicationId})'"></button>
<button class="button3" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 3, id = Model.ApplicationId})'"></button>
<button class="button4" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 4, id = Model.ApplicationId})'"></button>
<button class="button5" type="button" onclick="location.href='@Url.Action("eRate", "Rating", new { rating = 5, id = Model.ApplicationId})'"></button>