AdamPersonalCapstone/AdamPersonalCapstone/Controllers/CustomerDevicesJTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdamPersonalCapstone.Models;
using Microsoft.AspNet.Identity;

namespace AdamPersonalCapstone.Controllers
{
    public class CustomerDevicesJTablesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult AddDevice(int id)
        {
            var userId = User.Identity.GetUserId();
            var customer = db.Customers.Where(c => c.ApplicationId == userId).FirstOrDefault();
            CustomerDevicesJTable customerDevicesJTable = new CustomerDevicesJTable();
            customerDevicesJTable.DevicesId = id;
            customerDevicesJTable.CustomerId = customer.CustomerId;
            db.CustomerDevices.Add(customerDevicesJTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteDevice(int id)
        {
            var userId = User.Identity.GetUserId();
            var customer = db.Customers.Where(c => c.ApplicationId == userId).FirstOrDefault();
            CustomerDevicesJTable customerDevicesJTable = new CustomerDevicesJTable();
            customerDevicesJTable.DevicesId = id;
            customerDevicesJTable.CustomerId = customer.CustomerId;
            db.CustomerDevices.Remove(customerDevicesJTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: CustomerDevicesJTables
        public ActionResult Index()
        {
            var customerDevices = db.CustomerDevices.Include(c => c.Customer).Include(c => c.Device);
            return View(customerDevices.ToList());
        }

        // GET: CustomerDevicesJTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerDevicesJTable customerDevicesJTable = db.CustomerDevices.Find(id);
            if (customerDevicesJTable == null)
            {
                return HttpNotFound();
            }
            return View(customerDevicesJTable);
        }

        // GET: CustomerDevicesJTables/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "ApplicationId");
            ViewBag.DevicesId = new SelectList(db.Devices, "DevicesId", "Brand");
            return View();
        }

        // POST: CustomerDevicesJTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerDevicesJTableId,DevicesId,CustomerId")] CustomerDevicesJTable customerDevicesJTable)
        {
            if (ModelState.IsValid)
            {
                db.CustomerDevices.Add(customerDevicesJTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "ApplicationId", customerDevicesJTable.CustomerId);
            ViewBag.DevicesId = new SelectList(db.Devices, "DevicesId", "Brand", customerDevicesJTable.DevicesId);
            return View(customerDevicesJTable);
        }

        // GET: CustomerDevicesJTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerDevicesJTable customerDevicesJTable = db.CustomerDevices.Find(id);
            if (customerDevicesJTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "ApplicationId", customerDevicesJTable.CustomerId);
            ViewBag.DevicesId = new SelectList(db.Devices, "DevicesId", "Brand", customerDevicesJTable.DevicesId);
            return View(customerDevicesJTable);
        }

        // POST: CustomerDevicesJTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerDevicesJTableId,DevicesId,CustomerId")] CustomerDevicesJTable customerDevicesJTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customerDevicesJTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "ApplicationId", customerDevicesJTable.CustomerId);
            ViewBag.DevicesId = new SelectList(db.Devices, "DevicesId", "Brand", customerDevicesJTable.DevicesId);
            return View(customerDevicesJTable);
        }

        // GET: CustomerDevicesJTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerDevicesJTable customerDevicesJTable = db.CustomerDevices.Find(id);
            if (customerDevicesJTable == null)
            {
                return HttpNotFound();
            }
            return View(customerDevicesJTable);
        }

        // POST: CustomerDevicesJTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustomerDevicesJTable customerDevicesJTable = db.CustomerDevices.Find(id);
            db.CustomerDevices.Remove(customerDevicesJTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdamPersonalCapstone/AdamPersonalCapstone/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdamPersonalCapstone.Models;

namespace AdamPersonalCapstone.Controllers
{
    public class DevicesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Devices
        public ActionResult Index()
        {
            return View(db.Devices.ToList());
        }

        // GET: Devices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // GET: Devices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DevicesId,Brand,Name")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Devices.Add(device);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(device);
        }

        // GET: Devices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DevicesId,Brand,Name")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Entry(device).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(device);
        }

        // GET: Devices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Device device = db.Devices.Find(id);
            db.Devices.Remove(device);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdamPersonalCapstone/AdamPersonalCapstone/Views/CustomerDevicesJTables/Create.cshtml
@model AdamPersonalCapstone.Models.CustomerDevicesJTable

@{
    ViewBag.Title = "Create";
}

<h1 style="color:deepskyblue; text-align:center">Create</h1>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CustomerDevicesJTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DevicesId, "DevicesId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DevicesId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DevicesId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a class="badge" style="color: deepskyblue" @Html.ActionLink("Back to List", "Index")></a>
</div>

AdamPersonalCapstone/AdamPersonalCapstone/Views/CustomerDevicesJTables/Delete.cshtml
@model AdamPersonalCapstone.Models.CustomerDevicesJTable

@{
    ViewBag.Title = "Delete";
}
<head>
    <style>
        .img-container {
            text-align: center;
            display: block;
        }
    </style>
</head>
<body>
    <h1 style="color:deepskyblue; text-align:center">Delete</h1>

    <h3 style="color:deepskyblue; text-align:center">Are you sure you want to delete this?</h3>
    <div>
        <h4></h4>
        <hr />
        <dl class="dl-horizontal">
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    <span class="img-container">
        <img src="~/Content/Image/nhn3.png" alt="Neighborhood Nerd Logo">
    </span>
</body>

AdamPersonalCapstone/AdamPersonalCapstone/Views/CustomerDevicesJTables/Details.cshtml
@model AdamPersonalCapstone.Models.CustomerDevicesJTable

@{
    ViewBag.Title = "Details";
}

<h1 style="color:deepskyblue; text-align:center">Details</h1>

<div>
    <h4>CustomerDevicesJTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.ApplicationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.ApplicationId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Device.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device.Brand)
        </dd>

    </dl>
</div>
<p>
    <a class="badge" style="color: deepskyblue"@Html.ActionLink("Edit", "Edit", new { id = Model.CustomerDevicesJTableId })></a>
    <a class="badge" style="color: deepskyblue"@Html.ActionLink("Back to List", "Index")></a>
</p>

AdamPersonalCapstone/AdamPersonalCapstone/Views/CustomerDevicesJTables/Edit.cshtml
@model AdamPersonalCapstone.Models.CustomerDevicesJTable

@{
    ViewBag.Title = "Edit";
}

<h1 style="color:deepskyblue; text-align:center">Edit</h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CustomerDevicesJTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerDevicesJTableId)

        <div class="form-group">
            @Html.LabelFor(model => model.DevicesId, "DevicesId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DevicesId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DevicesId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a class="badge" style="color: deepskyblue" @Html.ActionLink("Back to List", "Index")></a>
</div>

AdamPersonalCapstone/AdamPersonalCapstone/Views/CustomerDevicesJTables/Index.cshtml
@model IEnumerable<AdamPersonalCapstone.Models.CustomerDevicesJTable>

@{
    ViewBag.Title = "Index";
}

<head>
    <style>
        .img-container {
            text-align: center;
            display: block;
        }
    </style>
</head>
<body>
    <div class="jumbotron" style="text-align:center">
        <h1 style="color:deepskyblue; text-align:center">Owned Devices</h1>
        @*<a class="badge" style="color: deepskyblue" @Html.ActionLink("Add New Device", "Index", "Devices")</a>*@
        <span class="img-container">
            <img src="~/Content/Image/nhn3.png" alt="Neighborhood Nerd Logo">
        </span>
        <a class="badge" style="color: deepskyblue" @Html.ActionLink("Add New Device", "Index", "Devices")</a>
        <br />
        <div class="container-fluid">
            <table class="table" style="color:deepskyblue">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Device.Brand)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Device.Name)
                    </th>
                    <th></th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Device.Brand)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Device.Name)
                        </td>
                        <td>
                            <<a class="badge" style="color: deepskyblue" @Html.ActionLink("Delete", "Delete", new { id = item.CustomerDevicesJTableId })></a>
                        </td>
                        <td>
                            <<a class="badge" style="color: deepskyblue" @Html.ActionLink("Create Ticket", "Create", "Tickets")></a>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
    </body>